//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Equipment { get; set; }
        public string FaultType { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
